name: taddib3-compose

services:
  app:
    image: taddib3-image
    container_name: taddib3-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: ["python", "/app/restaurant/manage.py", "runserver", "0.0.0.0:8000"]
