# Generated by Django 5.1.6 on 2025-03-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_category_cate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cate_image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
